### ISSUE TITLE
Cannot work with directory of vtt files

### ISSUE THREAD

**Issue by SaiTejaMummadi** [jsonzilla/vtt_to_srt3#2]
Traceback (most recent call last):
  File "path\Documents\audicut\vtts_to_srtttt.py", line 1, in <module>
    from vtt_to_srt import vtts_to_srt
ImportError: cannot import name 'vtts_to_srt' from 'vtt_to_srt' (C:\path\Programs\Python\Python37\lib\site-packages\vtt_to_srt\__init__.py)
[Finished in 0.4s]

**Comment by jsonzilla** [comment]
Fixed in 0.1.8.4.
