### ISSUE TITLE
No module named 'vtt_to_srt'

### ISSUE THREAD

**Issue by johan456789** [jsonzilla/vtt_to_srt3#3]
I have ran

```
pip install vtt_to_srt3
```

and it said `Successfully installed vtt-to-srt3-0.1.8.4`.

But can't import the module. Why?

**Comment by neel-bp** [comment]
i have fixed your issue and made a pull request, you can also just clone my fork https://github.com/neelu0/vtt-to-srt.py
and just do `python setup.py install` while being inside the project folder, make sure uninstall the older version first, by `pip uninstall vtt_to_srt3` after installing my fork you can use the program from anywhere just do `vtt_to_srt /path/to/file.srt` from terminal

**Comment by jsonzilla** [comment]
Thanks!

**Comment by bricksdont** [comment]
Very helpful change, but now the documentation should be updated to explain that running from the command line can now be done like this:

    vtt_to_srt ...

(without the `.py` at the end)
